### ISSUE TITLE
Workflow Rule Formula Editor in Lightning not working

### ISSUE THREAD

**Issue by JodieM** [kpeterson85/Salesforce-Enhanced-Formula-Editor-Chrome-Extension#14]
In the Workflow Rule Formula Editor I can't click into the formula box when the Toggle editor is on. I can only use the regular editor. 

I thought this was just part of the app not working for Lightning, but it's still doing it now after the Lightning upgrade.

**Comment by JodieM** [comment]
It works if I get an error alert on the formula and the page refreshes and I'm still in the edit box, then I can continue editing. It just seems to be clicking into it the first time.

**Comment by JodieM** [comment]
If I edit the formula again, it works. Hmm, this is weird.

**Comment by kpeterson85** [comment]
It looks like this occurs when adding a new workflow rule and selecting the formula option from the dropdown.  Most likely an issue with the formula box being shown after the fact.  If you edit an existing workflow that is already setup to use a formula, the editor loads correct.  Thanks for pointing this out!  I'll work in an update for it.

**Comment by JodieM** [comment]
Ah, I'm not going crazy then! Good!

**Comment by kpeterson85** [comment]
@JodieM This issue should be resolved once you receive the automated update to the latest version of the extension (1.4.4).  Let me know if you are still experiencing it.  Thanks!
