### ISSUE TITLE
Format issue

### ISSUE THREAD

**Issue by frankverrill** [kpeterson85/Salesforce-Enhanced-Formula-Editor-Chrome-Extension#20]
Hi 
Format function inserts a space in the literal Pi and causes the validation to fail.

Formats this: ROUND((3 .14159 * (Radius__c ^ 2) * Height__c), 0)
Should be this: ROUND((3.14159 * (Radius__c ^ 2) * Height__c), 0)

Minor bug as I worked around by turning off the formatter to validate.

**Comment by frankverrill** [comment]
I'm updating this issue as the Extension seems to insert a space in all decimal numbers between the integer and the decimal.  One other note that not supporting || && is problematic. 
The cursor seems to jump around a lot and seems the extension is not stable.
I hope these issues are resolved as I like the formatting of the formulas.

Another area would be to format formulas in Process Builder.  Perhaps an upcharge to the users for more functionality.

**Comment by kpeterson85** [comment]
Thank you for providing examples of the issues you were having.  I plan to look into these in the next round of updates.

**Comment by frankverrill** [comment]
Got the refund. Thanks
Stay in touch with updates.


Best regards,


Frank Verrill

Nuvol Direct

(714) 350-9553<tel:(714)%20350-9553>


CONFIDENTIALITY NOTICE: This electronic message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, copying, use, disclosure or distribution of any parts of the contents of this message/information is prohibited by federal law. Attempts to intercept this message are in violation of Title 18 USC 2511(1) of the Electronic Communications Privacy Act (ECPA), which subjects the interceptor to fines, imprisonment and/or civil damages. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

On Nov 17, 2018, at 8:10 AM, Kyle Peterson <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for providing examples of the issues you were having. I plan to look into these in the next round of updates.

**Comment by kpeterson85** [comment]
@frankverrill Formatting when decimals are present should be fixed now.  Please try again and let me know if you experience issues.
