### ISSUE TITLE
load record values isn't working

### ISSUE THREAD

**Issue by gibbamanda** [kpeterson85/Salesforce-Enhanced-Formula-Editor-Chrome-Extension#21]
I have had this extension for a couple of years but I just noticed that the load record values no longer works.  Please advise what the problem could be?

**Comment by kpeterson85** [comment]
Can you provide a screenshot of the formula you are working with.  Also please provide a screenshot of the Load Field Details area so I can see what fields it found in the formula since the Load Record Values feature tries to query the fields that were found.  If you know how to, you can also open the Chrome developer tools and see if there is an error in the console log and provide that.

**Comment by gibbamanda** [comment]
![err](https://user-images.githubusercontent.com/45105441/49087868-a8840d80-f21d-11e8-85db-b8fdec2fa527.png)

![image](https://user-images.githubusercontent.com/45105441/49087979-ea14b880-f21d-11e8-8135-ca13f50dac5e.png)


I have a attached a video with the formula and what happens when you try to load field details.
Below is a screenshot of the chrome developer tool console
[cid:image001.png@01D47FE1.E236FA50]

**Comment by kpeterson85** [comment]
I do not see any attachments to this issue.  Maybe you replied to the email with attachments.  Can you try attaching them to a comment directly within github?

**Comment by gibbamanda** [comment]
Yes I did reply to the email with the attachments.
I have now added 2 screenshots to the thread, but it doesn’t support mp4 so I couldn’t add the video

**Comment by kpeterson85** [comment]
I still do not see any attachments.

**Comment by gibbamanda** [comment]
https://github.com/kpeterson85/Salesforce-Enhanced-Formula-Editor-Chrome-Extension/issues/21#issuecomment-439911064
[cid:image001.png@01D486FB.B0FD2380]

**Comment by kpeterson85** [comment]
Please log in to github and attach files by dragging and dropping them into the comment box.

**Comment by gibbamanda** [comment]
![err](https://user-images.githubusercontent.com/45105441/49227458-c46ae900-f3ae-11e8-901e-e9a4e8f20836.png)

**Comment by gibbamanda** [comment]
![image](https://user-images.githubusercontent.com/45105441/49227654-2e838e00-f3af-11e8-807b-f2897ddd4e62.png)

**Comment by kpeterson85** [comment]
@gibbamanda This issue should be fixed now.  Let me know if you are still experiencing issues.

Thanks!

**Comment by gibbamanda** [comment]
I just tried again and it is still not loading the record values

**Comment by kpeterson85** [comment]
Can you go to chrome’s extension manager page and make sure you are on the latest version 1.5.2? If you are, can you check the browser console log and see if there is a different error?

**Comment by gibbamanda** [comment]
That worked.  Thank you
