### ISSUE TITLE
Salesforce.com Enhanced Formula Editor - Just bought, doesn't work...

### ISSUE THREAD

**Issue by Eric123445324234234** [kpeterson85/Salesforce-Enhanced-Formula-Editor-Chrome-Extension#23]
I just bought this chrome extension only to see that NOTHING changes. It doesn't highlight anything... Please, help!! I need to use it for work.

It's sitting in the upper right hand corner of the browser and everything seems ready to go but it just isn't doing anything. Screenshot below of me in Process Builder and look, it isn't helping at all:

![image](https://user-images.githubusercontent.com/49041725/55187511-7e544500-5156-11e9-92d6-9c4ad6faf72b.png)

**Comment by kpeterson85** [comment]
Hi Eric,

When you visit a formula edit page it will automatically enhance the formula textarea with a code editor.  This includes formula fields, validation rule formulas, workflow rule formulas, and field update formulas.  It does not include process builders though, sorry.
