### ISSUE TITLE
Feature Request - Formulas in Flows

### ISSUE THREAD

**Issue by JodieM** [kpeterson85/Salesforce-Enhanced-Formula-Editor-Chrome-Extension#25]
It's official, Flows will NOT be getting any love for the formula editor any time soon. (See https://youtu.be/HTgJO_oHjBk?t=3444). The Flow team seems to say that people who build Formulas in Flows already know how to build formulas so don't need anything fancier than a text box to write formulas directly in Flows. SO, if there is any way we could get even just syntax hi-lightning in the Formula boxes in Flows, then that would be amazing and wonderful! And I would even pay extra for that!

**Comment by kpeterson85** [comment]
@JodieM What are the common places where formulas are used within flows?

From a quick review I found these locations:
- a validation rule formula for a flow input field
- a formula resource under the flow manager tab

Any others that I'm missing?

**Comment by andydesanctis** [comment]
Yes you can use formulas in Process Builder criteria. I'd actually love to use your product there

**Comment by JodieM** [comment]
@kpeterson85 Those two, plus maybe text templates. But I would be very happy and forever grateful if it was only for the Formula Resource. 

I would love it in Process Builder, but Process Builder has its own issues and isn't well built, and they are only really putting effort into developing Flows now. I would love to have the time to spend on documenting the various incarnations of formula and criteria selection options in Salesforce and how they are all different and mostly quite bad. The new criteria selection in Lightning Reports is the better option, at least it has colours and parentheses that highlight and it is somewhat smart when you remove fields. It's like they actually looked at Kyle's plugin when they built that part, but then completely forgot about it again when they built list view and lightning page component criteria filters .

**Comment by kpeterson85** [comment]
@JodieM Using the formula editor extension with Flow formulas seems unlikely after reviewing .  The Flow editor UI makes use of shadow DOMs which makes it impossible to query for elements on pages like normal.  The difficulty is by design so it would be very hard to overcome.

@andydesanctis I reviewed the Process Builder page and it could be more promising.

**Comment by JodieM** [comment]
Ah thanks for checking it out at least @kpeterson85. I don't think Process Builder is worth doing since they have publicly stated they are not putting any more effort into Process Builder.  Yeah, on the Admins podcast this week John Kucera said that the new Flow builder is made with LWC so the shadow dom is understandable then.

**Comment by kpeterson85** [comment]
@JodieM After investigating this idea more, the in-between solution I've come up with is providing a button that opens the enhanced formula editor in a popup window. It would automatically copy your formula back and forth between the two editors as you make changes. It is not as seamless as replacing the normal formula editor but would at least provide the enhanced editor when you want to use it. You could insert resource placeholders using the normal editor and then pop open the enhanced editor to add logic and formatting. Would this be a helpful solution still?

This approach could make it easier to support other difficult areas like process builder formulas and reports formulas.

### New button to pop open the enhanced editor
<kbd><img src="https://user-images.githubusercontent.com/105022/108924556-d9279d00-7608-11eb-93de-5a510ee52830.png" width="600" /></kbd>

### Editor in a popup window.
Clicking Save Formula would update the formula in the normal editor so you can click Done.
<kbd><img src="https://user-images.githubusercontent.com/105022/108924784-5226f480-7609-11eb-979e-833f179fa3b3.png" width="700"/></kbd>

**Comment by JodieM** [comment]
Sounds perfect Kyle, as long as it can handle all the different collection variable names, like $Record $Record__prior or whatever its named in other flows. I'm very happy to be an alpha tester for this and help in any way. You have my email through the billing portal or DM me on twitter.

**Comment by kpeterson85** [comment]
The new Open Enhanced Formula Editor button is now available for Flows and Process Builders with the 2.0 version of the extension. @andydesanctis please let me know if you have any feedback with using it for Process Builders.
