### ISSUE TITLE
Formula editor  icon on Mac not working

### ISSUE THREAD

**Issue by chirugithub** [kpeterson85/Salesforce-Enhanced-Formula-Editor-Chrome-Extension#26]
Hi 

I purchased this formula editor and when i click on the chrome extension it's not working.

can you please help me.

thanks
Chiru

**Comment by kpeterson85** [comment]
@chirugithub When you visit a formula edit page it should automatically enhance the formula textarea with a code editor. This includes formula fields, validation rule formulas, workflow rule formulas, and field update formulas. Are you on one of these types of formula edit pages? Please provide screenshots and more details please.
