### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by Kristi-Anne** [kpeterson85/Salesforce-Enhanced-Formula-Editor-Chrome-Extension#28]
Hi there, I'm new to GitHub and the formula editor. I bought it last year (and paid for it twice, now), but have only had the chance to use it today. I'm writing because the extension is not working. Nothing is loading. It is essentially a dead button. Clicking it does nothing. If someone could tell me why it's no longer working, or if this extension has been discontinued, that would be great. Thank you!

**Comment by Kristi-Anne** [comment]
Nevermind... I'm an idiot. Found the toggle editor feature.

**Comment by kpeterson85** [comment]
Hi @Kristi-Anne the enhanced formula editor should show automatically when on a formula edit page.  The toggle editor checkbox is provided in case someone wants to turn it off after it has loaded by default. If the enhanced editor is not showing by default and you have to click toggle editor to see it then there could be a conflict occurring with another chrome extension.  You could try disabling some other extensions to see if you can get it to show on initial load. Let me know if you end up narrowing it down.

**Comment by Kristi-Anne** [comment]
Hi Kyle,

Thank you so much for getting back to me. After I posted my ticket, I realized the editor was actually working, but then I refreshed my page and nothing I did was able to bring the editor back. I also don’t have a checkbox to toggle the editor. I will try disabling other extensions to see if that fixes the issue! I will follow up if I can’t figure it out. Thank you!
