### ISSUE TITLE
"Error describing object 'Case'. It may only be accessible from a newer version of the API or you may not have meta data api access. Error message: Session expired or invalid"

### ISSUE THREAD

**Issue by Groverhouse** [kpeterson85/Salesforce-Enhanced-Formula-Editor-Chrome-Extension#30]
**Things to Try First**
- Try disabling other Salesforce extensions, there may be a conflict
There is only a adobe extension that I disabled. 
- Make sure you are on the latest version of the extension

**Details to Include**
 - Are you on Salesforce Classic or Lightning?
Either
- Were you editing a Standard object or a Custom object.  If Standard, which one?
Standard, Case or Account 
- What version of the extension are you on?
Version 1.5.4
- Check the browser console log and provide any errors you see
jsforce-core.min.js:4 GET https://mgroves-20200317-demo.my.salesforce.com/services/data/v48.0/sobjects/Case/describe 401 (Unauthorized)

activate_editor.js:257 INVALID_SESSION_ID: Session expired or invalid
    at k.getError (chrome-extension://cnlnnpnjccjcmecojdhgpknalcahkhio/jsforce-core.min.js:3:23763)
    at chrome-extension://cnlnnpnjccjcmecojdhgpknalcahkhio/jsforce-core.min.js:3:22114
    at d (chrome-extension://cnlnnpnjccjcmecojdhgpknalcahkhio/jsforce-core.min.js:7:28673)
    at chrome-extension://cnlnnpnjccjcmecojdhgpknalcahkhio/jsforce-core.min.js:7:28946
    at p.d.promiseDispatch (chrome-extension://cnlnnpnjccjcmecojdhgpknalcahkhio/jsforce-core.min.js:7:23206)
    at chrome-extension://cnlnnpnjccjcmecojdhgpknalcahkhio/jsforce-core.min.js:7:21978
    at Array.b (chrome-extension://cnlnnpnjccjcmecojdhgpknalcahkhio/jsforce-core.min.js:7:26369)
    at c (chrome-extension://cnlnnpnjccjcmecojdhgpknalcahkhio/jsforce-core.min.js:6:21476)
- Provide screenshot of the page and what the editor was doing
When I load the extension the browser console has those errors and when I select "Load Details" for the formula editor below the error message "Error describing object 'Case'. It may only be accessible from a newer version of the API or you may not have meta data api access. Error message: Session expired or invalid" appears

This seems to be security related and I am not sure what I am missing from my user record perspective because I have Modify All Data Permissions in this demo org. 

![image](https://user-images.githubusercontent.com/74740424/99724838-13612b80-2a69-11eb-83ca-ad317d88f7d5.png)
- Provide a copy of the formula
8*(IF( ISNULL( DateTime_Closed_c__c  ), NOW() -  DateTime_Opened_c__c ,  DateTime_Closed_c__c  -  DateTime_Opened_c__c ))

**Comment by kpeterson85** [comment]
@Groverhouse Thank you for the great details! I have confirmed that I am experiencing the issue too. There must have been a recent change that is affecting the extension. I will investigate and let you know the status of it.

**Comment by Groverhouse** [comment]
Super! Let me know if there would be any other details from an end user that would be helpful. 

General feedback: I am new to the tool and really like it so far!

**Comment by kpeterson85** [comment]
@Groverhouse I released a fix in version 1.5.5 which hopefully has been auto downloaded to your browser by now. Once you have the latest version can you try the Load Field Details button again and see if you experience the issue still?
