### ISSUE TITLE
New Subscription

### ISSUE THREAD

**Issue by lejomesa** [kpeterson85/Salesforce-Enhanced-Formula-Editor-Chrome-Extension#33]
Good morning team,

Hope you guys have an amazing year.

I just received a notification for the Salesforce Enhace Formula editor license, It suggest to move to the new subscription model, but I recently acquired a year subscription,it doesn't make sense to me to acquire a new year subscription since I recently bought one.

Could you please provide information or let me know how should I proceed? 

I don't want to deactivate that extension since its pretty useful, but If I'm double paying for an annual subscription then I will.

Regards,

**Comment by kpeterson85** [comment]
@lejomesa I followed up with you through email. Thank you
