### ISSUE TITLE
Fuzzy Text

### ISSUE THREAD

**Issue by JodieM** [kpeterson85/Salesforce-Enhanced-Formula-Editor-Chrome-Extension#5]
I have noticed just recently that all the text is fuzzy (shadowed) and the cursor does not show in the correct place. 

I know this is a known issue in visualforce code when you have the browser set to > 100% zoom, but I have double checked this and I'm definitely on 100% and it doesn't make any difference which zoom level it's on. 

It is mainly the light blue text in quotes that is the issue with shadowing, but the cursor issue is throughout the whole formula.

The shaddowing is worse the further right in the formula it goes. 

I have created a [screen shot](https://thedetaildept.gyazo.com/9d2dfdb230945343b3f209e8e5e41120) of the issue.

I have checked it on different monitors. (I have recently got a new Surface Pro 4, but I don't know how that could be an issue, and I don't know if I spotted it before then or not). 

How else could I do some debugging to help you identify what is causing this issue? 

I'm on version Version 49.0.2623.112 m of Chrome

**Comment by JodieM** [comment]
Just marking this that it is still an issue. I love this extension and I would love a fix for it.

**Comment by kpeterson85** [comment]
Hi Jodie, is this still an issue for you?

**Comment by JodieM** [comment]
Hasn't been for a while, so I will go ahead and close this.
