### ISSUE TITLE
Update Display

### ISSUE THREAD

**Issue by LifeMeansChange** [kpeterson85/Salesforce-Enhanced-Formula-Editor-Chrome-Extension#6]
I received a popup about the newest updates for Enhanced Formula Builder. The popup is taller than my window and won't allow me to scroll down. I'm not able to close the window at all which is preventing me from access my formula field all together. What can I do to resolve. Also, I posted this question in the google Chrome web store. Is there a way to delete that comment?

**Comment by kpeterson85** [comment]
I'll deploy an update this week that removes the new version message.

**Comment by kpeterson85** [comment]
The version message was removed last week (#7).
