### ISSUE TITLE
Lightning Support

### ISSUE THREAD

**Issue by ghost** [kpeterson85/Salesforce-Enhanced-Formula-Editor-Chrome-Extension#9]
I have noticed this excellent tool is not supported in lightening. Is this something that is possible to rectify?

**Comment by JodieM** [comment]
Yes please! @kpeterson85. Now that Summer '17 is released, and the Object Manager is now useable, I find myself wanting to go into Lightning more and more to do Setup. But having relied on your extension for so long now, it's really hard to go without it. 

(Also, can you fix the spelling of this item please).

**Comment by AnSFDCAdmin** [comment]
Our organization is moving to lightning within the next 2 months and not looking forward to losing this extension.  This is one of the best tools an admin can have.  Hopefully you're working on a fix soon for us all that use this!

**Comment by kpeterson85** [comment]
I have updated the extension to work within lightning.  Your browser should prompt you for new extension permissions to lightning if you have received the latest update (1.4.3).  Please run through some tests and let me know if you come across any issues.
